### ISSUE TITLE
[Feature] 상품 기능 개발

### ISSUE THREAD

**Issue by iqveou6** [T-RaMis8khae/Starbucks_BackEnd#28]
## 주요 내용
상품 기능 개발

## todo

- [x]  상품 조회 기능 개발
- [x] 상품 상세 기능 개발
- [x] 카테고리 기능 개발
