### ISSUE TITLE
[Feature] 카테고리 기능 개발

### ISSUE THREAD

**Issue by iqveou6** [T-RaMis8khae/Starbucks_BackEnd#45]
### 주요 내용
카테고리 기능 개발

### todo

- [x] top 카테고리 기능 개발
- [x] middle 카테고리 기능 개발
- [x] bottom 카테고리 기능 개발
