### ISSUE TITLE
[Feature] 이벤트 기능 개발

### ISSUE THREAD

**Issue by tlswl7479** [T-RaMis8khae/Starbucks_BackEnd#54]
### 주요 내용
이벤트 기능 개발

### todo

- [x] 이벤트 조회 기능 개발
- [ ] 크롤링 이벤트 추가 기능 개발
- [x] 이벤트 삭제 기능 개발
